# This docker-compose file sets up and runs the YOLO e-commerce app using Docker containers.
# It includes services for the frontend (React), backend (Node.js), and database (MongoDB).

# To get started:
# 1. Clone this repository.
# 2. Make sure Docker and Docker Compose are installed on your system.
# 3. Run `docker compose up --build` from the root of the project directory.

# This will automatically build and launch the app in your browser at http://localhost.

version: "3.3"

services:
  # Frontend Service (React built and served via Nginx)
  yolo-client:
    image: misaro/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:80"  # NGINX serves on port 80 internally
    depends_on:
      - yolo-backend
    stdin_open: true
    tty: true
    networks:
      - yolo-net

  # Backend Service (Node.js/Express + Mongoose)
  yolo-backend:
    image: misaro/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overwriting node_modules
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - yolo-net



# Docker Bridge Network for Container Communication
networks:
  yolo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16



