- name: Deploy E-commerce App with Docker
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - role: database
      tags: db
    - role: backend
      tags: backend
    - role: client
      tags: client
