---
# tasks file for roles/backend


- name: Install Docker Engine
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes
