apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ecommerce
type: Opaque
stringData:
  uri: "mongodb+srv://username:password@cluster0.mongodb.net/dbname?retryWrites=true&w=majority"
