apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: ecommerce
type: Opaque
stringData:
  uri: "mongodb+srv://misaro:Misarobt1@yolo.03ovfcw.mongodb.net/?retryWrites=true&w=majority&appName=yolo"
