---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - docker.io

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
