---
- name: Deploy E-commerce App with Docker
  hosts: all
  become: yes

  vars_files:
     vars/main.yml

  roles:

    - ecommerce
    - database
    - common
    - backend
    - client
    - compose_up
