---
- name: Ensure Docker CLI plugin directory exists
  file:
    path: /usr/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Check for existing Docker Compose CLI plugin binary
  stat:
    path: /usr/lib/docker/cli-plugins/docker-compose
  register: compose_plugin
  become: true

- name: Download Docker Compose CLI plugin binary if missing
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64"
    dest: /usr/lib/docker/cli-plugins/docker-compose
    mode: '0755'
  when: not compose_plugin.stat.exists
  become: true

- name: Pull latest Docker images via Compose plugin binary
  command: /usr/lib/docker/cli-plugins/docker-compose pull
  args:
    chdir: "{{ compose_dir | default('/home/vagrant/ecommerce') }}"
  become: true

- name: Bring up services with Docker Compose plugin binary
  command: /usr/lib/docker/cli-plugins/docker-compose up -d
  args:
    chdir: "{{ compose_dir | default('/home/vagrant/ecommerce') }}"
  register: compose_up
  failed_when: compose_up.rc != 0
  changed_when: compose_up.stdout is search("Creating|Starting")
  become: true

