---
# roles/compose_up/tasks/main.yml

- name: Ensure Docker CLI plugin directory exists
  file:
    path: /usr/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Bring down any existing Compose stack (ignore errors)
  ansible.builtin.shell: docker compose down --remove-orphans
  args:
    chdir: "{{ compose_dir | default('/home/vagrant/ecommerce') }}"
  ignore_errors: yes
  become: true

- name: Pull latest images from Compose file
  ansible.builtin.shell: docker compose pull
  args:
    chdir: "{{ compose_dir | default('/home/vagrant/ecommerce') }}"
  become: true

- name: Start services with Docker Compose
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "{{ compose_dir | default('/home/vagrant/ecommerce') }}"
  register: compose_up
  failed_when: compose_up.rc != 0
  changed_when: "'Creating' in compose_up.stdout or 'Starting' in compose_up.stdout"
  become: true
